spring:
  application:
    name: springboot-redisson-ms
  redis:
    cluster:
      nodes: 192.168.56.200:6379,192.168.56.200:6380,192.168.56.200:6381 # 多个使用逗号分隔
    password: yuanfenge@redis
    database: 0
