## rabbitmq消息消费者配置
server:
  port: 9002

spring:
  application:
    name: springboot-cloud-stream-rabbitmq-listener
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.56.200  # rabbit服务地址
                port: 5672
                username: yuanfenge
                password: yuanfenge
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: CustomerExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          group: yuanfenge_group # 相同分组的服务只有一个能消费消息，并且消息可以持久化

