# 使用druid数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      db-type: com.alibaba.druid.pool.DruidDataSource
      # 配置druid监测 访问地址 http://127.0.0.1/8080/druid/
      stat-view-servlet:
        allow: 127.0.0.1 # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
        login-username: admin # 访问用户名
        login-password: 123456 # 访问密码
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"   # 排除一些不必要的资源
  thymeleaf:
    cache: false

mybatis:
  type-handlers-package: com.yuanfenge.mybatis.druid.typehandler
  mapperLocations: classpath:mapper/**.xml
  typeAliasesPackage:  com.yuanfenge.mybatis.druid.bean
  # 开启自动映射
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
    auto-mapping-behavior: full